### ISSUE TITLE
Installation & android app

### ISSUE THREAD

**Issue by yashinfotech1018** [CanciuCostin/android-spyware#34]
Sir how to install it on live web server and where is the android app source code ?? unable to find

**Comment by CanciuCostin** [comment]
Hi! I will try to document the project in the near future, as soon as I get some time. The project leverages Metasploit framework to generate the Android app, so thats why you can't find any source code for it.

**Comment by Panwar005** [comment]
> Hi! I will try to document the project in the near future, as soon as I get some time. The project leverages Metasploit framework to generate the Android app, so thats why you can't find any source code for it.

Pls provide installation guide.

**Comment by CanciuCostin** [comment]
@yashinfotech1018  @Panwar005 
The readme is now updated with all the necessery steps for deployment.
Thank you for the patience.
