### ISSUE TITLE
Installation Instruction

### ISSUE THREAD

**Issue by yashinfotech1018** [CanciuCostin/android-spyware#35]
Sir please guide us how to install and run this project on live server.

**Comment by sabriallani** [comment]
How to install and run it please?

**Comment by CanciuCostin** [comment]
Hi! I will try to document the project in the near future, as soon as I get some time

**Comment by CanciuCostin** [comment]
@yashinfotech1018 @sabriallani 
The readme is now updated with all the necessery steps for deployment.
Thank you for the patience.
