### ISSUE TITLE
How to install it ?

### ISSUE THREAD

**Issue by yonfluxdrive** [CanciuCostin/android-spyware#36]
Hello,
man, how to install it pls ?

**Comment by CanciuCostin** [comment]
Hi! I will try to document the project in the near future, as soon as I get some time

**Comment by JayRebuilds** [comment]
pls do, your standing between me and my new job

**Comment by CanciuCostin** [comment]
@JayRebuilds @JayRebuilds 
The readme is now updated with all the necessery steps for deployment.
Thank you for the patience.
